language: go

# fzgo is not yet a proper module, including the tests would need to be updated.
env:
  - GO111MODULE=off
  
matrix:
  include:
    - os: linux
      go: "1.16.x"
    - os: linux
      go: "1.15.x"
#    - os: linux
#      go: "1.14.x"
#    - os: osx
#      go: "1.16.x"
#    - os: osx
#      go: "1.15.x"
    - os: windows
      go: "1.16.x"
#    - os: windows
#      go: "1.15.x"

before_install:
  # TODO: Sigh. Travis seems to have old ca-certificates or similar issue, or at least, git complains and fails...
  - git config --global http.sslverify false
  - go get -v -u github.com/dvyukov/go-fuzz/...
  - go get -v -u golang.org/x/tools/cmd/goimports

script:
  - go test ./fuzz ./randparam ./genfuzzfuncs
  - go test -short .
  - go test ./...
